version: '3.9'


services:
  db:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: aiohttp_task